### ISSUE TITLE
Unneeded calls to cache layer

### ISSUE THREAD

**Issue by vanputten** [batenburg/caching-bundle#1]
**Description**
When you call the cache repository multiple times with the same key, it will always make a call to it's caching layer to fetch the results even if it has already fetched the exact same result before in the same request.

In our specific use case, this resulted in hitting our memcached 80 times on 1 request, with ~25ms per call the gain was 2s by storing the memcached result in a private property.

**Possible solution**
Since without preloading PHP will instance a new instance of the cache repository for every request, there should not be too much trouble if the cache layer stores the cache result in a private property so it can be reused if requested again within the same request.

**Simple example to demonstrate the idea**
`private array $results = [];`

    `public function getItem(string $key, $default = null): CacheItemInterface
    {
        $item = $this->results[$key] ?? $this->cacheAdapter->getItem($key);

        if ($this->needsToEscapeToDefault($item, $default)) {
            $item->set($this->resolveDefault($default));
        }

       $this->results[$key] = $item;

        return $item;
    }`

**Comment by batenburg** [comment]
The function `getItem` is resolving a value from the cash. If it is not set, it will set the default value and return it. However it is not performing a `save` on this item. 

This package is providing two ways for this. Either after retrieving the item you call `saveItem`, with the key and the value. Personally I consider this be a bad practice. 

A good practice solution would be to call `rememberItem`, so the data will be saved after resolving. I think this is the way you would like to go.
